language: python
python:
  - 3.7
branches:
  only:
    - master

install:
  - pip install numpy
  - pip install tensorflow
  - pip install word2vec
  # - pip install codecov

script:
  - python ./机器学习写诗/poet_master/main.py 2
  # - python ./规则写诗/poetize.py
  # - python ./机器学习写诗/lyrics_writer/main.py 1 -cd modern
